DROP TABLE IF EXISTS encoding_queue;
//#STATEMENT
DROP TABLE IF EXISTS encoding_queue_item;
//#STATEMENT
DROP TABLE IF EXISTS access;
//#STATEMENT
DROP TABLE IF EXISTS circ_rules;
//#STATEMENT
DROP TABLE IF EXISTS course_aliases;
//#STATEMENT
DROP TABLE IF EXISTS course_instance_audit;
//#STATEMENT
DROP TABLE IF EXISTS course_instances;
//#STATEMENT
DROP TABLE IF EXISTS course_instance_audit;
//#STATEMENT
DROP TABLE IF EXISTS courses;
//#STATEMENT
DROP TABLE IF EXISTS courses_no_dept;
//#STATEMENT
DROP TABLE IF EXISTS departments;
//#STATEMENT
DROP TABLE IF EXISTS electronic_item_audit;
//#STATEMENT
DROP TABLE IF EXISTS help_art_tags;
//#STATEMENT
DROP TABLE IF EXISTS help_art_to_role;
//#STATEMENT
DROP TABLE IF EXISTS help_art_to_art;
//#STATEMENT
DROP TABLE IF EXISTS help_articles;
//#STATEMENT
DROP TABLE IF EXISTS help_cat_to_role;
//#STATEMENT
DROP TABLE IF EXISTS help_categories;
//#STATEMENT
DROP TABLE IF EXISTS hidden_readings;
//#STATEMENT
DROP TABLE IF EXISTS ils_requests;
//#STATEMENT
DROP TABLE IF EXISTS inst_loan_periods;
//#STATEMENT
DROP TABLE IF EXISTS inst_loan_periods_libraries;
//#STATEMENT
DROP TABLE IF EXISTS instructor_attributes;
//#STATEMENT
DROP TABLE IF EXISTS item_upload_log;
//#STATEMENT
DROP TABLE IF EXISTS items;
//#STATEMENT
DROP TABLE IF EXISTS libraries;
//#STATEMENT
DROP TABLE IF EXISTS mimetype_extensions;
//#STATEMENT
DROP TABLE IF EXISTS mimetypes;
//#STATEMENT
DROP TABLE IF EXISTS news;
//#STATEMENT
DROP TABLE IF EXISTS not_trained;
//#STATEMENT
DROP TABLE IF EXISTS notes;
//#STATEMENT
DROP TABLE IF EXISTS permissions_levels;
//#STATEMENT
DROP TABLE IF EXISTS physical_copies;
//#STATEMENT
DROP TABLE IF EXISTS proxied_hosts;
//#STATEMENT
DROP TABLE IF EXISTS proxies;
//#STATEMENT
DROP TABLE IF EXISTS reports;
//#STATEMENT
DROP TABLE IF EXISTS reports_cache;
//#STATEMENT
DROP TABLE IF EXISTS requests;
//#STATEMENT
DROP TABLE IF EXISTS reserves;
//#STATEMENT
DROP TABLE IF EXISTS skins;
//#STATEMENT
DROP TABLE IF EXISTS special_users;
//#STATEMENT
DROP TABLE IF EXISTS special_users_audit;
//#STATEMENT
DROP TABLE IF EXISTS staff_libraries;
//#STATEMENT
DROP TABLE IF EXISTS target_table_mapping;
//#STATEMENT
DROP TABLE IF EXISTS terms;
//#STATEMENT
DROP TABLE IF EXISTS user_view_log;
//#STATEMENT
DROP TABLE IF EXISTS users;

